rango/urls.py
from django.urls import path
from rango import views
from django.conf.urls import url

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    # path('search/', views.search, name='search'),
    path('category/<slug:category_name_slug>/add_comment/', views.add_comment, name='add_comment'),
    path('suggest/', views.CategorySuggestionView.as_view(), name='suggest'),
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^like/$', views.like_category, name='like_category'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.utils import timezone
import os

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    cleaned_data = {}
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url']=url
        if url and not url.endswith('/'):
            url = f'{url}/'
            cleaned_data['url']=url
        return cleaned_data
    def __str__(self):
        return self.title



def get_file_path(instance, filename):
    ext = 'jpg'
    filename = "%s.%s" % (instance, ext)
    return os.path.join('profile_images', filename)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to=get_file_path , blank=True)

    def __str__(self):
        return self.user.username

def anonymousProfile():
    return UserProfile.objects.get(name='default')
class Comment(models.Model):
    # when delete a user, we want to keep the comments he posted on blog posts, but say it was posted by an anonymous (or deleted) user
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    username = models.CharField(max_length=150)
    timesmp = models.DateTimeField(default=timezone.now)
    content = models.CharField(max_length=2000)
    
    def __str__(self):
        return self.content

rango/forms.py
from django.utils import timezone
from django import forms
from rango.models import Comment, Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

class CommentForm(forms.ModelForm):
    content = forms.CharField(max_length=2000,widget=forms.Textarea(attrs={'rows': 5,'cols': 80}))
    class Meta:
        model = Comment
        fields = ('content',)

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from rango.models import Category,Page,Comment
from rango.forms  import CategoryForm, CommentForm, PageForm, UserForm, UserProfileForm
from django.shortcuts import redirect
from rango.forms import PageForm
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
from rango.bing_search import run_query
from django.conf import settings
from pathlib import Path
from django.views import View


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    context_dict['extra'] = 'From the model solution on GitHub'

    visitor_cookie_handler(request)

    return render(request, 'rango/index.html', context=context_dict)


def about(request):
    # Spoiler: now you DO need a context dictionary!
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/about.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        comment = Comment.objects.filter(category=category).order_by('-timesmp')
        context_dict['pages'] = pages
        context_dict['category'] = category
        # comment form
        form = CommentForm()
        context_dict['form'] = form
        for c in comment:
            print(c.username)
            path = Path(settings.MEDIA_ROOT+'/profile_images/'+c.username+'.jpg')
            c.pic_exist = path.exists()
        context_dict['comments'] = comment

    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None
        context_dict['comments'] = None
        context_dict['form'] = None
        context_dict['pic_exist'] = None

    query = ''

    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            context_dict['result_list'] = run_query(query)
            context_dict['query'] = query

    return render(request, 'rango/category.html', context=context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None

    # You cannot add a page to a Category that does not exist... DM
    if category is None:
        return redirect(reverse('rango:index'))

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)  # This could be better done; for the purposes of TwD, this is fine. DM.

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
        
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
            
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
        
    return render(request, 'rango/register.html', context = {'user_form': user_form,
                                                             'profile_form': profile_form,
                                                             'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")

        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html')

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


def add_comment(request,category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    if category is None:
        return redirect(reverse('rango:index'))
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            print('valid')
            if category:
                comment = form.save(commit=False)
                comment.category = category
                print(request)
                if request.user.is_authenticated:
                    comment.username = request.user.username
                else:
                    comment.username = "Anonymous"
                comment.save()
                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print('not valid')
            print(form.errors)
    
    show_category(request,category_name_slug)
def get_category_list(max_results=0, starts_with=''):
    category_list = []
    if starts_with:
        category_list = Category.objects.filter(name__istartswith=starts_with)
    if max_results > 0:
        if len(category_list) > max_results:
            category_list = category_list[:max_results]
    return category_list


class CategorySuggestionView(View):
    def get(self, request):
        if 'suggestion' in request.GET:
            suggestion = request.GET['suggestion']
        else:
            suggestion = ''

        category_list = get_category_list(max_results=8, starts_with=suggestion)

        if len(category_list) == 0:
            category_list = Category.objects.order_by('-likes')

        return render(request, 'rango/categories.html', {'categories': category_list})


def track_url(request):
    page_id = None
    url = '/rango/'
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
    try:
        page = Page.objects.get(id=page_id)
        page.views = page.views + 1
        page.save()
        url = page.url
    except:
        pass
    return redirect(url)

@login_required
def like_category(request):
    categoryId = None
    if request.method == 'GET':
        categoryId = request.GET['category_id']
        likes = 0
        if categoryId:
            category = Category.objects.get(id = int(categoryId))
            if category:
                likes = category.likes +1
                category.likes = likes
                category.save()
    return HttpResponse(likes)

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
<section class="content-head">
    <h1>Rango says...</h1>
</section>
    <div>
        here is the about page. <br />
        This tutorial has been put together by Webster.<br />
        <p>Visits: {{ visits }}</p>
    </div>
<img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
<img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
<section class="content-head">
    <h1>Add a Category</h1>
</section>
<div>
    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <button type="submit" name="submit" value="Create Category" class="button button-blue" >Create Category</button>
    </form>
</div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
<section class="content-head">
    <h1>Add a Page to {{ category.name }}</h1>
</section>
<div>
    <form id="add_page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
        {% csrf_token %}
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <button type="submit" name="submit" value="Add Page" class="button button-blue">Add Page</button>
    </form>
</div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}


<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Rango -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
        <link rel="shortcut icon" href="{%static 'images/vegetable_chicken.ico' %}" type="image/x-icon" />
        <link rel="stylesheet" href="{%static 'style/base.css' %}">
        
        {% block sheet_block %}
        {% endblock %}
    </head>

    <body>
        <div class="main">
            <nav class="header">
                <ul>
                    <li><a class="nav-link"  href="{% url 'rango:index' %}">Home</a></li>
                    <li><a class="nav-link"  href="{% url 'rango:about' %}">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="nav-link"  href="{% url 'rango:restricted' %}">Restricted</a></li>
                    <li><a class="nav-link"  href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                    <li><a class="nav-link"  href="{% url 'rango:add_category' %}">Add Category</a></li>
{#                    <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>#}
{#                    <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>#}
{#                    <li class="nav-item"><a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a></li>#}
                    {% else %}
                    <li><a class="nav-link"  href="{% url 'rango:register' %}">Register Here</a></li>
                    <li><a class="nav-link"  href="{% url 'auth_login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </nav>
            <div class="app">
                <aside>
                    <div>
                        <div id="sidebar">
                           <div>
                              <input type="search" id="search-input" class="ds-input" placeholder="Search..." />
                           </div>
           
                            <div class="sidebar-sticky" id="categories-listing">
                               {% block sidebar_block %}
                                   {% get_category_list category %}
                               {% endblock %}
                            </div>
                        </div>
                   </div>
                </aside>
                <article>
                {% block body_block %}
                {% endblock %}
                </article>
            </div>
        </div>

    <script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
    <script src="{% static "js/rango-ajax.js" %}" crossorigin="anonymous"></script>
    </body>
</html>

templates/rango/categories.html
<ul>
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
        <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
        {% else %}
        <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{%load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block sheet_block %}
<link rel="stylesheet" href="{%static 'style/category.css' %}">
{% endblock %}

{% block body_block %}
    {% if category %}
    <section class="content-head">
        <h1>{{ category.name }}</h1>
        <div>
            <strong id="like_count">{{ category.likes }}</strong> people like this category
            {% if user.is_authenticated %}
            <button id="likes" data-catid="{{category.id}}" class="button button-blue" type="button">
                LIKE!
            </button>
            {% endif %}
        </div>
    </section>


    <div>
        <form id="user-form" method="post" action="{% url 'rango:show_category' category.slug %}">
            {% csrf_token %}
            <input class="inline-top query" type="text" size="50" name="query" id="query" value="{{ query }}"/>
            <button class="button button-blue inline-top" type="submit" name="submit">Search</button>
            {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}" class="button button-green inline-top">Add Page</a> <br />
            {% endif %}
        </form>
    </div>
    
    {% if pages %}
    <ul class="list">
        {% for page in pages %}
        <li>
            <a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
            {% if page.views > 1 %}
                ({{ page.views }} views)
            {% elif page.views == 1 %}
                ({{ page.views }} view)
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <strong class="placeholder">No pages currently in category.</strong>
    {% endif %}
    <div class="list-result">
        {% if result_list %}
        <h2>Results</h2>
        <div class="list-group">
            {% for result in result_list %}
            <div class="list_group-item">
                <h3 class="list-group-item-heading">
                    <a href="{{ result.link }}">
                        {{ result.title|safe|escape }}
                    </a>
                </h3>
                <p class="list-group-item-heading">
                    {{ result.summary|safe|escape }}
                </p>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>

    {% else %}
        <p class="placeholder">The specified category does not exist.</p>
    {% endif %}
    <div>
        <div>
            <form id="comment_form" method="post" action="{% url 'rango:add_comment' category.slug %}">
                {% csrf_token %}
                <div class="fieldWrapper">
                    {{ form.content.errors }}
                    <label for="{{ form.content.id_for_content }}"><b>Comment:</b></label>
                    {{ form.content }}
                    <button id="commentCommit" type="submit" class="button button-blue" style="margin-top: 0;">Submit</button>
                </div>
                <!-- <input type="textarea" name="content" value=""  cols="50" rows="5"/> -->
            </form>
        </div>
        {% if comments %}
        <ul class="comment-ul">
            {% for comment in comments %}
            <li class="comment-li">
                <p>
                    {% if comment.pic_exist %}
                    <img src="{{ MEDIA_URL }}profile_images/{{ comment.username }}.jpg" height="30" width="30" alt="Picture of user">
                    {% else %}
                    <img src="{{ MEDIA_URL }}profile_images/Anonymous.jpg"" height="30" width="30" alt="Picture of user">
                    {% endif %}
                    <span class="username">{{ comment.username }}</span>
                    <span class="timesmp">{{ comment.timesmp }}</span>
                </p>
                <div class="content">
                    <p>{{ comment.content }}</p>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <p class="placeholder">The comment does not exist.</p>
        {% endif %}
    </div>
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block sheet_block %}
<link rel="stylesheet" href="{%static 'style/index.css' %}">
{% endblock %}

{% block body_block %}
<section class="content-head">
    <h1>Rango says ...</h1>
    <div>
        {% if user.is_authenticated %}
            howdy {{ user.username }}!
        {% else %}
            hey there partner!
        {% endif %}
        <br />
        <strong>{{ boldmessage }}</strong><br />
    </div>
</section>

<div class="flex-box">
    <div class="block">
        <h2>Most Liked Categories</h2>
    {% if categories %}
        <ul>
        {% for category in categories %}
            <li><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <strong class="placeholder">There are no categories present.</strong>
    {% endif %}

    </div>

    <div class="block">
        <h2>Most Viewed Pages</h2>
    {% if pages %}
        <ul>
        {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <strong class="placeholder">There are no pages present.</strong>
    {% endif %}
    </div>

</div>

<img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" style="margin-top: 10px;"/>
{% endblock %}
 

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<section class="content-head">
<h1>Login to Rango</h1>
</section>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    <div class="fieldWrapper">
        <label for="username">Username</label> <input type="text" id="username" name="username" value="" size="50" />
    </div>
    <div class="fieldWrapper">
        <label for="password">Password</label> <input id="password" type="password" name="password" value="" size="50" />
    </div>
    <div class="fieldWrapper">
        <button type="submit" value="" class="button button-blue">Submit</button>
    </div>
</form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block sheet_block %}
<link rel="stylesheet" href="{%static 'style/register.css' %}">
{% endblock %}

{% block body_block %}
<section class="content-head">
    <h1>Register for Rango</h1>
    {% if registered %}
    <p>Rango says: <strong>thank you for registering!</strong></p>
<a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
{% else %}
<p>Rango says: <strong>register here!</strong><br /></p>
</section>
<form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="fieldWrapper">
        {{ user_form.username.errors }}
        <label for="{{ user_form.subject.id_for_username }}">Username:</label>
        {{ user_form.username }}
    </div>
    <div class="fieldWrapper">
        {{ user_form.email.errors }}
        <label for="{{ user_form.email.id_for_email }}">Email:</label>
        {{ user_form.email }}
    </div>
    <div class="fieldWrapper">
        {{ user_form.password.errors }}
        <label for="{{ user_form.password.id_for_password }}">Password:</label>
        {{ user_form.password }}
    </div>
    <div class="fieldWrapper">
        {{ profile_form.website.errors }}
        <label for="{{ profile_form.website.id_for_website }}">Website:</label>
        {{ profile_form.website }}
    </div>
    <div class="fieldWrapper">
        {{ profile_form.picture.errors }}
        <label for="{{ profile_form.picture.id_for_picture }}">Picture:</label>
        {{ profile_form.picture }}
    </div>
    <button type="submit" name="submit" value="Register" class="button button-blue">Register</button>
</form>
{% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
<section class="content-head">
    <h1>Restricted Page</h1>
</section>
Since you're logged in, you can see this text!<br />
{% endblock %}